# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 自动更新

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 4/6 * * *"

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 下载 Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装依赖项
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: 自动更新
      run : |
        python main.py
